# Generated by Django 2.2.19 on 2021-03-15 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ratting', '0001_initial'),
        ('attraction', '0001_initial'),
        ('comment', '0001_initial'),
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TouristSpot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='nome')),
                ('description', models.TextField(blank=True, null=True, verbose_name='descrição')),
                ('approved', models.BooleanField(default=False, verbose_name='aprovado')),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adresses', to='address.Address', verbose_name='endereço')),
                ('attractions', models.ManyToManyField(blank=True, to='attraction.Attraction', verbose_name='atrações')),
                ('comments', models.ManyToManyField(blank=True, to='comment.Comment', verbose_name='comentários')),
                ('rattings', models.ManyToManyField(blank=True, to='ratting.Ratting', verbose_name='avaliações')),
            ],
            options={
                'verbose_name': 'ponto turístico',
                'verbose_name_plural': 'pontos turísticos',
                'ordering': ('name',),
            },
        ),
    ]
